### ISSUE TITLE
Fix flake support

### ISSUE THREAD

**Issue by MalpenZibo** [MalpenZibo/ashell#10]
Fix nix flake configuration.

**Comment by IceDBorn** [comment]
Please, I want to try it so baaaad. I wish I could help, but I have no idea how to build rust packages.

**Comment by MalpenZibo** [comment]
Well, I just merged a PR that "should" fix the flake configuration. I say "should" because right now I don't have Nix installed or a Nix-os system to test it :D

In the future, I will try to install nix on my Arch Linux machine and try it there. Anyway I'm not sure if everything works on nix-os

**Comment by IceDBorn** [comment]
it does not.

**Comment by MalpenZibo** [comment]
Ok, I have finally installed Nix on my arch linux machine and in this branch https://github.com/MalpenZibo/ashell/tree/10_add-nix-support, I created a working flake configuration. I don't know if everything works on a NixOS machine but it should be installable.
