### ISSUE TITLE
Add flake install instructions

### ISSUE THREAD

**Issue by nonetrix** [MalpenZibo/ashell#2]
Would be helpful for new users imo

**Comment by nonetrix** [comment]
Also failing to build it anyway, but could be doing something wrong. https://github.com/fufexan/ashell builds though but throws 
```
ERROR [ashell] Panic: panicked at /build/cargo-vendor-dir/iced_sctk-0.1.0/src/application.rs:226:10:
Failed to initialize the event loop: NoWaylandLib
```

**Comment by MalpenZibo** [comment]
For sure, right know I'm on holiday but I plan to fix this issue soon

**Comment by MalpenZibo** [comment]
The nix package should work now! I will close this issue, feel free to reopen it in case of problem
