### ISSUE TITLE
AUR package  / offical package

### ISSUE THREAD

**Issue by nonetrix** [MalpenZibo/ashell#3]
Title is enough

**Comment by nonetrix** [comment]
Or maybe crazy and kinda stupid idea, why not a flatpak? Or Appimage etc. Is there any reason you couldn't in theory? Also could package it in Cargo I think?

**Comment by MalpenZibo** [comment]
I never create an AUR package. I should do some research. I'm not sure that something like flatpack is the right solution for something like a status bar

**Comment by MalpenZibo** [comment]
I created the first package in the AUR repository. It's my first package so I hope that works fine, I'm currently using it.
https://aur.archlinux.org/packages/ashell-git

**Comment by MalpenZibo** [comment]
Ok! I created also the package for the tagged release https://aur.archlinux.org/packages/ashell
