### ISSUE TITLE
Does not connect to dbus

### ISSUE THREAD

**Issue by fiersik** [MalpenZibo/ashell#44]
After fixing the last problem, I was able to build a package, but the panel categorically refuses to display icons and connect to DBus.

![image](https://github.com/user-attachments/assets/0b14d2c6-0b90-4750-b06e-038caf59a55c)

```shell
INFO [ashell::config] Reading config file
WARN [wgpu_hal::gles::egl] Re-initializing Gles context due to Wayland window
ERROR [ashell::services::privacy] Failed to connect to pipewire or webcam data
ERROR [ashell::services::privacy] Privacy service error
ERROR [ashell::services::brightness] Brightness service error
ERROR [ashell::services::network] Failed to initialize network service: No such file or directory (os error 2)
ERROR [ashell::services::network] Network service error
```

Is this a problem on my side?

**Comment by fiersik** [comment]
Oh, I was able to fix the icons, but dbus didn't work

**Comment by MalpenZibo** [comment]
Hum... it could be something related to some permission. Are you running ALT Linux? I don't know much about that distribution but maybe is something related to user permission. The dbus service is running ok? There are some dbus logs that could be useful to better understand the problem? Your user can run the `dbus-monitor` command just to check if you can receive some messages?

**Comment by fiersik** [comment]
> Your user can run the `dbus-monitor` command just to check if you can receive some messages?

Yes, and other panels, such as waybar, also work

**Comment by fiersik** [comment]
I have an ironbar panel, it is also written in Rust and works great

**Comment by MalpenZibo** [comment]
Ok, I noticed that the `power_profile` button is present. It works? Because if it working then is not a dbus problem but something else

**Comment by fiersik** [comment]
> It works?

Oh, yeah, that's the only thing that works. ,- ,
But since it is also tied to dbus, then the problem is not in dbus and not in access rights (Otherwise, it wouldn't work either.)...

To be honest, now I don't understand at all what the problem might be.

**Comment by MalpenZibo** [comment]
The network service problem could be caused by the fact that your system is not present the `rfkill` command. I should handle that part better because in theory shouldn't be a hard dependency. If you can install that program and try to see if resolves the network service error log would be great, meanwhile I will prepare a fix to that.

For the Brightness service, I have an `unwrap()` during the init that could cause the problem. It seems strange because I didn't expect a problem there but if you can show me the content of the directory `/sys/class/backlight` would be great.

For the Privacy service, do you have the following file `/dev/video0`? Again I'm not handling very well some cases. I will open a PR with some changes (maybe adding some other log :D)

**Comment by fiersik** [comment]
> is not present the `rfkill` command.

OH, rfkill is located on the path /usr/sbin/rfkill in my system, creating a symbolic link in /usr/bin/ saved me from this problem!!! is it possible to take this feature of the system into account in future releases?

> if you can show me the content of the directory /sys/class/backlight would be great.

Sorry! Brightness service is not really a problem, it turns out I broke this feature throughout the system.

**Comment by MalpenZibo** [comment]
Ok in reality for the Brightness service the problem is different. I think that is caused here
```
let actual_brightness_file = device_path.join("actual_brightness");
let inotify = Inotify::init()?;
```

In my case, the `/sys/class/backlight` has an `amdgpu_bl1` folder that contains an `actual_brightness` file. Without that file, the service cannot start

**Comment by fiersik** [comment]
> Ok in reality for the Brightness service the problem is different. I think that is caused here

I'll check it on another device later, but now it seems I've been able to fix all the problems!
the only problem is the different location of rfkill in my system, could you provide for that?

**Comment by MalpenZibo** [comment]
> > is not present the `rfkill` command.
> 
> OH, rfkill is located on the path /usr/sbin/rfkill in my system, creating a symbolic link in /usr/bin/ saved me from this problem!!! is it possible to take this feature of the system into account in future releases?
> 
> > if you can show me the content of the directory /sys/class/backlight would be great.
> 
> Sorry! Brightness service is not really a problem, it turns out I broke this feature throughout the system.

Hum, usually should work if it's in the `PATH`. I will make a change to avoid the error if that command is not in the PATH.

**Comment by fiersik** [comment]
> Hum, usually should work if it's in the PATH.

The /usr/sbin path is intended for root, by default the user does not have it in the $PATH variable



> I will make a change to avoid the error if that command is not in the PATH.

That would be great!

**Comment by MalpenZibo** [comment]
Here is a PR with some fixes and more logs if you want make some test: https://github.com/MalpenZibo/ashell/pull/45

For the `rfkill` command if you can call `rfkill` from the terminal then, in theory, also ashell should be able to.
I'm doing 
```
        let output = Command::new("rfkill")
            .arg("list")
            .arg("bluetooth")
            .output()
            .await?;
```
and I prefer to rely on the `PATH` instead of using absolute path

**Comment by MalpenZibo** [comment]
> > Hum, usually should work if it's in the PATH.
> 
> The /usr/sbin path is intended for root, by default the user does not have it in the $PATH variable
> 
> > I will make a change to avoid the error if that command is not in the PATH.
> 
> That would be great!

hum. ok! I will try with a fallback value

**Comment by fiersik** [comment]
> hum. ok! I will try with a fallback value

Thank you very much! I will be very grateful, but if for some reason this is not possible, I could patch this moment only for ALT

**Comment by MalpenZibo** [comment]
I pushed a commit where I use the absolute path, Let me know if resolves the problem

**Comment by fiersik** [comment]
> I pushed a commit where I use the absolute path, Let me know if resolves the problem

This did fix the problem for me, but now Bluetooth is displayed in the panel (there is no Bluetooth on my PC)

**Comment by MalpenZibo** [comment]
> > I pushed a commit where I use the absolute path, Let me know if resolves the problem
> 
> This did fix the problem for me, but now Bluetooth is displayed in the panel (there is no Bluetooth on my PC)

ahha perfect! I will try to resolve this issue

**Comment by MalpenZibo** [comment]
Ok, I should have resolve

**Comment by fiersik** [comment]
This does not apply to this problem, but it seems to me that this should not be the case!

![image](https://github.com/user-attachments/assets/8ed43125-9e82-4fba-b956-0567d7843989)
![image](https://github.com/user-attachments/assets/71311e3c-713c-4d65-aa82-557ffc62ba9a)

the VPN button looks normal, although it can be expanded to the list, as well as wifi

I'm sorry if I should have written about this in a separate issue.

**Comment by MalpenZibo** [comment]
In theory, the VPN button open/close the VPN menu with all the VPN present in the system (it should appear only if there's at least one VPN). In that menu, you can enable or disable a VPN connection with that toggle.

The button should be orange (in this case) only if at least one VPN is connected.

I don't understand the exact problem here. From what I can see, you have an active VPN connection so the VPN button is active (orange), and on click it opens the VPN menu that shows your current VPN connection with the toggle.

**Comment by fiersik** [comment]
Maybe...I didn't understand what I wanted myself.

Is it possible to make the same arrow for the list for VPN as for wifi, and by pressing the main button turn on/off the last active vpn?

It's more of a suggestion than a claim, I just didn't put it right.

**Comment by MalpenZibo** [comment]
Ok, could make sense. 
I'm not sure how to activate the last activated VPN (I have to save the state somewhere) and if there isn't any last active VPN then maybe open the menu? for sure when it's active clicking on the button can deactivate all the active VPNs.

I have to think about it. I just ask you if you can open a dedicated issue with this feature request/change.

Also if you can confirm that all the original issues have been resolved I will proceed with merging the PR and creating a new release.

**Comment by fiersik** [comment]
> for sure when it's active clicking on the button can deactivate all the active VPNs.

This sounds interesting, I'll create a separate issue to discuss it.

> Also if you can confirm that all the original issues have been resolved

Yes, all problems have been fixed, thank you!!

**Comment by MalpenZibo** [comment]
I released the new version. I think that this issue can be closed now
