### ISSUE TITLE
using fonts?

### ISSUE THREAD

**Issue by fiersik** [MalpenZibo/ashell#49]
Currently, only the Symbols Nerd Font is used to display icons, is it possible for the panel to find the appropriate font itself, and not use a specific one?

**Comment by MalpenZibo** [comment]
I'm currently using DejaVu for char and the Symbols Nerd Font for the icons.
I think a better approach could be to avoid specifying a particular font and letting iced use the default SansSerif font (or let the user specify a font via config) and use a nerd font patched for the icon.

Sadly, right now I have installed the DefaVu nerd font patch but without specifying anything I'm not able to see any icons. Probably I could simply include the required font icon in the binary

**Comment by MalpenZibo** [comment]
Why would you make this change? I prefer to add the Symbols Nerd Font as a hard dependency of the project.

**Comment by fiersik** [comment]
There are some problems with the assembly of nerd fonts, but this is not critical. This is just a suggestion to make it possible to use another nerd font

**Comment by MalpenZibo** [comment]
What do you mean by "another nerd font"? I'm currently using some glyphs present in the SymbolsNerdFont (mainly the material one) so I cannot use another font for the icons

**Comment by fiersik** [comment]
Ohh, then I'll think about how to assemble this font

**Comment by MalpenZibo** [comment]
In this [PR](https://github.com/MalpenZibo/ashell/pull/51) I will put the symbols font into the package binary, I'm not sure if this can fix your problem.

**Comment by fiersik** [comment]
I have already assembled the font in a separate package, I think this is no longer necessary, I'm sorry

**Comment by MalpenZibo** [comment]
Ok, in a future release, I could embed the symbols font anyway in the binary to simplify the packaging of the application.

**Comment by fiersik** [comment]
it would be great if it doesn't greatly affect the size of the binary file.

**Comment by MalpenZibo** [comment]
it should add 2MB to the binary file

**Comment by fiersik** [comment]
It sounds very good!

**Comment by fiersik** [comment]
The new version of ashell has stopped displaying icons, although the font should be compiled into the main file

**Comment by MalpenZibo** [comment]
That's very strange o.O I will try to understand why

**Comment by fiersik** [comment]
Apparently, the font still does not compile, since installing a third-party font helps

**Comment by MalpenZibo** [comment]
I tried with the iced 13 branch and everything works correctly. So It could be something iced 12 related (or related to my layer to access the wayland layer shell protocol).

In any case right now the only possible solution is to install the font as dependency or wait until the iced13 switch

**Comment by fiersik** [comment]
Oh, good

**Comment by fiersik** [comment]
Oh, good

**Comment by MalpenZibo** [comment]
This issue should be resolved with the new Iced 14-based version in the main branch. When you have time could you try and let me know?

**Comment by fiersik** [comment]
Hurray! It really helped! Everything works.
