### ISSUE TITLE
Opening a special workspace breaks the workspace indicator

### ISSUE THREAD

**Issue by fiersik** [MalpenZibo/ashell#62]
When opening a special workspace, the workspace indicator stops working, hangs on the last workspace that was active before the special workspace was opened.

when creating a special workspace, the following message appears:
```
ERROR [ashell] Panic: panicked at alloc/src/raw_vec.rs:24:5:
capacity overflow
```

**Comment by fiersik** [comment]
I also noticed that if there is at least one special workspace, it is not possible to start ashell, the process immediately crashes

This is most likely due to the fact that special workspaces use a negative ID, for example, -99

```
---> hyprctl workspaces
workspace ID 1 (1) on monitor HDMI-A-1:
	monitorID: 0
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x55e70a76ab10
	lastwindowtitle: Telegram (655)

workspace ID 2 (2) on monitor HDMI-A-1:
	monitorID: 0
	windows: 2
	hasfullscreen: 0
	lastwindow: 0x55e70bf111a0
	lastwindowtitle: hyprctl workspaces ~

workspace ID -99 (special:special) on monitor HDMI-A-1:
	monitorID: 0
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x55e70bf21160
	lastwindowtitle: ~
```

**Comment by fiersik** [comment]
I found some fixes [here](https://github.com/leftas/ashell)

**Comment by MalpenZibo** [comment]
Ups! I never used a special workspace :sweat_smile: 

I will change the workspace module to show every possible special workspace, displaying the name, and then the normal one.

**Comment by fiersik** [comment]
> I will change the workspace module to show every possible special workspace, displaying the name, and then the normal one.

It would be very cool!
It would be nice if they were displayed in a different color.

**Comment by MalpenZibo** [comment]
The color is bound to the workspace monitor. I could create a new set of workspace colors to use for the special workspaces.

**Comment by fiersik** [comment]
> I could create a new set of workspace colors to use for the special workspaces.

I think it's a good idea.

**Comment by MalpenZibo** [comment]
I have added this feature here #64 if you want to try

**Comment by fiersik** [comment]
![image](https://github.com/user-attachments/assets/515b9749-ecc9-4e71-8adc-30a709bfe28b)

I put it together from the last commit, it looks beautiful, the colors of the workspace buttons have started working.

Of the problems, I noticed that pressing the button of a special workspace always opens the first workspace. Most likely, this is due to the fact that another dispatcher is needed to open a special workspace: `togglespecialworkspace`

`togglespecialworkspace` without parameters opens a special workspace "special"
You can pass the name as a parameter

---------
```
hyprctl dispatch togglespecialworkspace 
hyprctl dispatch togglespecialworkspace special
```
Both of these commands will open a special workspace with the default name "special"
```
hyprctl dispatch togglespecialworkspace game
```
This command will open a special workspace "game"

---------

I think you need to check the workspace id, and if it is negative, then use the manager `togglespecialworkspace` and the name instead of the id

---------

![image](https://github.com/user-attachments/assets/a88f519a-ffae-46ed-a9f0-1ef641b7a9bd)

Here is the output of the `hyprctl workspaces` command
```
workspace ID -98 (special:game) on monitor HDMI-A-1:
	monitorID: 0
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x55904cf49eb0
	lastwindowtitle: ~

workspace ID -99 (special:special) on monitor HDMI-A-1:
	monitorID: 0
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x55904c8069c0
	lastwindowtitle: WGPU_BACKEND=gl ashell ~
```

**Comment by fiersik** [comment]
Oh, something got me carried away, it turned out to be a bit long, but it was informative)

**Comment by fiersik** [comment]
I noticed that the numbers of the workspaces are slightly higher than they should be (they are not located in the center), I thought that I had problems with the font, but ashell chooses the right one himself - Sansserif

**Comment by fiersik** [comment]
> but ashell chooses the right one himself - Sansserif

the font in my panel is too different anyway, it's weird

**Comment by MalpenZibo** [comment]
My system font for sans serif is dejavu. It's strange, I should make some test with other font. In my case it's ok 
Maybe could be something related to my HiDPI display (I hope not because in that case it's something that I cannot fix easily)

**Comment by fiersik** [comment]
> My system font for sans serif is dejavu.

The problem was solved by deleting all sans serif fonts in the system, except dejavu

But this method seems too crutchy.

**Comment by MalpenZibo** [comment]
For sure, I have to improve the rendering with other font other than dejavu

**Comment by fiersik** [comment]
I think this is not so critical, now you have so many important tasks.

**Comment by MalpenZibo** [comment]
I have changed the special workspace selection, and now it should work. Sadly I have to make a change to `hyprland-rs`, I hope that my PR on their repo will be merged soon.

**Comment by MalpenZibo** [comment]
I merged the PR, in case of a problem let me know or re-open the PR. For the font issue if you want you can open a new issue!
