### ISSUE TITLE
Add multi monitor support

### ISSUE THREAD

**Issue by MalpenZibo** [MalpenZibo/ashell#9]
Resolve https://github.com/MalpenZibo/ashell/issues/4

This feature cannot be implemented right now. Ashell is based on the work done by the system76 to let the Iced toolkit use the Wayland layer surface and right now it seems impossible to specify a target monitor but it's only possible to use the "Active" one.

**Comment by IceDBorn** [comment]
Does Iced13 include multi-monitor support?

**Comment by MalpenZibo** [comment]
Iced 13 doesn't have the concept of multi-monitor.

Here I'm using a library, based on the work of the pop_os team on their fork of iced that add the support for create Wayland layer shell. Sadly that library doesn't have a way to create a layer on a specific monitor or on multiple monitor.

I plan to change that library in favor of https://github.com/waycrate/exwlshelleventloop (see issue #24) that has that functionality and also support iced 13.

Right now the exwlshelleventloop team resolved two major bug that I have (one on multi monitor support and one with HiDPI display) but I still have some performance regression so I haven't merged #35 yet.

This change will resolve also other issue like #25 and #23 so will be my priority in the future.

**Comment by IceDBorn** [comment]
I'm looking forward to using ashell. I'll wait patiently until multi-monitor is supported.

**Comment by MalpenZibo** [comment]
It's been a while but I'm ready to merge this feature in the main branch https://github.com/MalpenZibo/ashell/pull/43
